### ISSUE TITLE
Configuration location

### ISSUE THREAD

**Issue by LinusU** [46elks/elkme#2]
I recently made a library to put the configuration in the correct place in Node.js. [Here is the different locations on different platforms.](https://github.com/LinusU/node-application-config#config-location)

It might help you :)

**Comment by sakjur** [comment]
Oh, looks awesome! I'll have to look into that ^_^ Thanks!

**Comment by sakjur** [comment]
:arrow_forward: :file_folder: :apple: :penguin: :confetti_ball:
